webtalk_init -webtalk_dir /home/rmoulin/4A/BE-Acces/Ethernet_Controller/Ethernet_Controller.sim/sim_1/behav/xsim/xsim.dir/test_recv_v0_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Mar 24 18:09:31 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "62b4fc5f-8418-4821-b167-454abc0805d1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "c0f47c8414f4431b8174b81b5ee2978d" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "195" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 20.04.6 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3300.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "114412_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1520320481 -regid "" -xml /home/rmoulin/4A/BE-Acces/Ethernet_Controller/Ethernet_Controller.sim/sim_1/behav/xsim/xsim.dir/test_recv_v0_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/rmoulin/4A/BE-Acces/Ethernet_Controller/Ethernet_Controller.sim/sim_1/behav/xsim/xsim.dir/test_recv_v0_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/rmoulin/4A/BE-Acces/Ethernet_Controller/Ethernet_Controller.sim/sim_1/behav/xsim/xsim.dir/test_recv_v0_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
